language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
